INSERT INTO state (abbreviation, name, region) VALUES ('AC', 'Acre', 'NORTE');
INSERT INTO state (abbreviation, name, region) VALUES ('AL', 'Alagoas', 'NORDESTE');
INSERT INTO state (abbreviation, name, region) VALUES ('AP', 'Amapá', 'NORTE');
INSERT INTO state (abbreviation, name, region) VALUES ('AM', 'Amazonas', 'NORTE');
INSERT INTO state (abbreviation, name, region) VALUES ('BA', 'Bahia', 'NORDESTE');
INSERT INTO state (abbreviation, name, region) VALUES ('CE', 'Ceará', 'NORDESTE');
INSERT INTO state (abbreviation, name, region) VALUES ('DF', 'Distrito Federal', 'CENTRO_OESTE');
INSERT INTO state (abbreviation, name, region) VALUES ('ES', 'Espírito Santo', 'SUDESTE');
INSERT INTO state (abbreviation, name, region) VALUES ('GO', 'Goiás', 'CENTRO_OESTE');
INSERT INTO state (abbreviation, name, region) VALUES ('MA', 'Maranhão', 'NORDESTE');
INSERT INTO state (abbreviation, name, region) VALUES ('MT', 'Mato Grosso', 'CENTRO_OESTE');
INSERT INTO state (abbreviation, name, region) VALUES ('MS', 'Mato Grosso do Sul', 'CENTRO_OESTE');
INSERT INTO state (abbreviation, name, region) VALUES ('MG', 'Minas Gerais', 'SUDESTE');
INSERT INTO state (abbreviation, name, region) VALUES ('PA', 'Pará', 'NORTE');
INSERT INTO state (abbreviation, name, region) VALUES ('PB', 'Paraíba', 'NORDESTE');
INSERT INTO state (abbreviation, name, region) VALUES ('PR', 'Paraná', 'SUL');
INSERT INTO state (abbreviation, name, region) VALUES ('PE', 'Pernambuco', 'NORDESTE');
INSERT INTO state (abbreviation, name, region) VALUES ('PI', 'Piauí', 'NORDESTE');
INSERT INTO state (abbreviation, name, region) VALUES ('RJ', 'Rio de Janeiro', 'SUDESTE');
INSERT INTO state (abbreviation, name, region) VALUES ('RN', 'Rio Grande do Norte', 'NORDESTE');
INSERT INTO state (abbreviation, name, region) VALUES ('RS', 'Rio Grande do Sul', 'SUL');
INSERT INTO state (abbreviation, name, region) VALUES ('RO', 'Rondônia', 'NORTE');
INSERT INTO state (abbreviation, name, region) VALUES ('RR', 'Roraima', 'NORTE');
INSERT INTO state (abbreviation, name, region) VALUES ('SC', 'Santa Catarina', 'SUL');
INSERT INTO state (abbreviation, name, region) VALUES ('SP', 'São Paulo', 'SUDESTE');
INSERT INTO state (abbreviation, name, region) VALUES ('SE', 'Sergipe', 'NORDESTE');
INSERT INTO state (abbreviation, name, region) VALUES ('TO', 'Tocantins', 'NORDESTE');